### ISSUE TITLE
react peerdependencies issue with react-soundplayer

### ISSUE THREAD

**Issue by lennart** [sleexyz/hylide#16]
I cannot get this to install properly, as it fails on `npm install` telling me that `react-soundplayer` wants `react@0.14.x` whereas the package.json file specifies `react@^15.0.1` and also `react-dom@^15.0.1` this situation seems to be unsolvable unless both react and react-dom are downgraded to a compatible version for react-soundplayer, since this is as of now not compatible with react 15.

It would be interesting how you did get this to install.

Kindly,

lennart

**Comment by sleexyz** [comment]
Hi @lennart, for some reason my package isn't building either, let me get back to you on this.

**Comment by sleexyz** [comment]
For some reason, `expose-loader` used to work properly with osc, and now it doesn't. Node and its non-deterministic builds ... :p

But hey, it should work now! I did a fresh clone with node 5.2.0 on OSX 10.11.2 and it works fine for me.

Let me know if you have any more questions!

**Comment by lennart** [comment]
hi,

I had to add express and ws to package.json to start the server. 

will create another issue since I cannot get hylogen and hylide to work together (maybe their versions do not match, as the data coming in Does not use the expected format... obj.tag is not defined, the json contains only the property "code")

for deterministic builds with nodejs I think they added npm shrinkwrap, though I didn't use it yet...

**Comment by sleexyz** [comment]
@lennart hmm do a `git pull`, I did an update to the new json api right after you filed the issue
