### ISSUE TITLE
does not work with hylogen 0.1.3.0

### ISSUE THREAD

**Issue by lennart** [sleexyz/hylide#19]
I got hylogen via cabal and tried to run the `Example.hs` from the readme, however hylide fails starting in `local.js` line 46 (compiled src) since the parsed json only contains the property `code` and no `tag`. 

If the haskell code contains errors it fails with an "unexpected error" (which since, it's live coding _will_ happen and therefor should be expected ;)), since error also just contains the property "error" and no "tag".

**Comment by sleexyz** [comment]
you need to hylogen 0.1.3.2, sorry for the less-than-ideal semantic  versioning. That's when I updated to the new json api.

Regarding error messaging, you should only get `unexpected error` if there's an error with the transport, i.e. incompatible JSON api. 
https://github.com/sleexyz/hylide/blob/master/src/local.js#L59

Under normal conditions, Haskell error messages should be sent over the wire:
https://github.com/sleexyz/hylide/blob/master/src/local.js#L56

**Comment by lennart** [comment]
0.1.3.2 is on cabal, no? otherwise I'll have to switch to git (which I could have dine in the first place) but will do tomorrow.

thx for the quick responses.

I'll be seeing whether hylogen/hylide can be interfaced with TidalCycles (http://tidalcycles.org) to get audio and graphics live coding, yay

**Comment by sleexyz** [comment]
yup! It's the latest version on hackage (as of this moment*). Let me know how it goes, I'm  very interested in what a potential audiovisual live-coding setup will look like!

* I'm gonna release hylogen 0.1.4.0, which is just going to contain the language. The server-side hylide stuff will move to this repo
